name: reviewdog
on: [pull_request]

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install black==23.1.0
      - uses: reviewdog/action-black@644053a260402bc4278a865906107bd8aef7fae8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning

  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
            | sh -s -- -b /usr/local/bin


      - name: Run analyzer with reviewdog
        run: |
          http://localhost:8382/review?source=github&url=https://github.com/${{ github.repository }}.git&change_id=${{ github.event.pull_request.number }}&message_format=reviewdog \
            | reviewdog -f=rdjson \
                -name="my-analyzer" \
                -reporter=github-pr-review \
                -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
