name: reviewdog
on: [pull_request]

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install black==23.1.0
      - uses: reviewdog/action-black@644053a260402bc4278a865906107bd8aef7fae8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install black==23.1.0

      - uses: reviewdog/action-black@644053a260402bc4278a865906107bd8aef7fae8

      - name: Run analyzer with reviewdog
        run: |
          cat fake.json \
            | reviewdog -f=rdjson \
                -name="my-analyzer" \
                -reporter=github-pr-review \
                -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
