name: reviewdog
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run analyzer with reviewdog
        run: |
          cat fake.json \
            | reviewdog -f=rdjson \
                -name="my-analyzer" \
                -reporter=github-pr-review \
                -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
